name: Release Docs

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'leanprover-community'
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Lean
        uses: leanprover/lean-action@v1
        with:
          test: false
          lint: false
          use-github-cache: true

      - name: Build Docs
        working-directory: docs
        run: lake build -q Batteries:docs

      - name: Compress Docs
        working-directory: docs
        env:
          TAG_NAME: ${{ github.ref_name }}
        run: |
          tar -czf docs-${TAG_NAME}.tar.gz doc doc-data
          zip -rq docs-${TAG_NAME}.zip doc doc-data

      - name: Release Docs
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ contains(github.ref, 'rc') }}
          make_latest: ${{ !contains(github.ref, 'rc') }}
          files: |
            docs/docs-${{ github.ref_name }}.tar.gz
            docs/docs-${{ github.ref_name }}.zip
          fail_on_unmatched_files: true
